apiVersion: v2
name: mssql-2019
description: A Helm chart for Kubernetes with MSSQL 2019
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mssql
  - database
  - relational
  - jnart
home: https://j-nart.com
maintainers:
- email: joao.alves@j-nart.com
  name: j-nart.com
